"""empty message

Revision ID: 94a9832779fd
Revises: 
Create Date: 2023-09-08 19:21:58.704293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a9832779fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ebay_account'))
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sa.String(length=8), nullable=True),
    sa.Column('verification_code_expiration', sa.DateTime(), nullable=True),
    sa.Column('notification_email', sa.String(length=345), nullable=True),
    sa.Column('notification_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_google_oauth', sa.Boolean(), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('ebay_user_id', sa.String(length=255), nullable=True),
    sa.Column('ebay_username', sa.String(length=255), nullable=True),
    sa.Column('ebay_refresh_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('ebay_username', name=op.f('uq_user_ebay_username'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ebay_user_id'), ['ebay_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_google_sub'), ['google_sub'], unique=True)

    op.create_table('snipe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('max_bid', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ebay_item_number', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('seller', sa.String(length=255), nullable=True),
    sa.Column('seller_feedback', sa.Integer(), nullable=True),
    sa.Column('current_bid', sa.Integer(), nullable=True),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Integer(), nullable=True),
    sa.Column('ending_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_snipe_user_id_user'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snipe'))
    )
    op.create_table('image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('snipe_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['snipe_id'], ['snipe.id'], name=op.f('fk_image_snipe_id_snipe'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('snipe')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_sub'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_ebay_user_id'))

    op.drop_table('user')
    op.drop_table('ebay_account')
    # ### end Alembic commands ###
