"""empty message

Revision ID: f300539768bf
Revises: 94a9832779fd
Create Date: 2023-09-08 19:26:20.950813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f300539768bf'
down_revision = '94a9832779fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebay_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ebay_user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ebay_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ebay_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ebay_account_user_id_user'), 'user', ['user_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebay_account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ebay_account_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('ebay_refresh_token')
        batch_op.drop_column('ebay_username')
        batch_op.drop_column('ebay_user_id')

    # ### end Alembic commands ###
